resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/dtspo-17345-reinstate-nagger-jg
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

  - name: kvConnectedServiceName
    type: string
    default: DCD-CFT-Sandbox

  - name: environments
    displayName: Environment to run
    type: object
    default:
      - deployment: 'neuvector'
        environment: 'sbox'
        dependsOn: 'Precheck'
        component: cft-neuvector
        service_connection: DCD-CFTAPPS-SBOX
      - deployment: 'neuvector'
        environment: 'ithc'
        dependsOn: 'Precheck'
        component: cft-neuvector
        service_connection: DCD-CFTAPPS-ITHC
      - deployment: 'neuvector'
        environment: 'perftest'
        dependsOn: 'Precheck'
        component: cft-neuvector
        service_connection: DCD-CFTAPPS-TEST
      - deployment: 'neuvector'
        environment: 'aat'
        dependsOn: 'Precheck'
        component: cft-neuvector
        service_connection: DCD-CFTAPPS-STG
      - deployment: 'neuvector'
        environment: 'ptl'
        dependsOn: 'Precheck'
        component: cft-neuvector
        service_connection: DTS-CFTPTL-INTSVC
      - deployment: 'neuvector'
        environment: 'prod'
        dependsOn: 'Precheck'
        component: cft-neuvector
        service_connection: DCD-CFTAPPS-PROD

  - name: location
    displayName: Location
    type: string
    default: 'UK South'

variables:
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - name: terraformVersion
    value: 0.14.5
  - name: globalTfCommandOptions
    value: -parallelism=1
  - name: timeoutInMinutes
    value: '60'
  - name: agentPool
    value: 'ubuntu-latest'
  - name: build
    value: $(Build.BuildNumber)
  - name: keyVaultName
    value: infra-vault-sandbox
  - name: secretsFilter
    value: azure-devops-sp-token
  - name: project
    value: application
  - name: product
    value: neuvector
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        displayName: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: ${{ variables.keyVaultName }}
              keyvaultSecret: ${{ variables.secretsFilter }}
              serviceConnection: ${{ parameters.kvConnectedServiceName }}
              overrideAction: ${{ parameters.overrideAction }}


  - ${{ each parameter in parameters.environments }}:
    - stage: ${{ parameter.environment }}
      displayName: ${{ parameter.environment }}
      dependsOn: ${{ parameter.dependsOn }}
      jobs:
        - job:
          pool:
            vmImage: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
            - template: "steps/terraform.yaml@cnp-azuredevops-libraries"
              parameters:
                tfVarsFile: NULL
                overrideAction: ${{ parameters.overrideAction }}
                environment: ${{ parameter.environment }}
                component: ${{ parameter.component }}
                kvConnectedServiceName: ${{ parameters.kvConnectedServiceName }}
                serviceConnection: ${{ parameter.service_connection }}
                terraformInitSubscription: ${{ variables.terraformInitSubscription }}
                product: ${{ variables.product }}
                ${{ if eq(parameter.environment, 'aat') }}:
                  initCommandOptions: -backend-config=resource_group_name=azure-control-stg-rg
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -backend-config resource_group_name=azure-control-stg-rg
                ${{ if eq(parameter.environment, 'perftest') }}:
                  initCommandOptions: -backend-config=resource_group_name=azure-control-test-rg
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -backend-config resource_group_name=azure-control-test-rg
                ${{ if eq(parameter.environment, 'ithc') }}:
                  initCommandOptions:
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }}
                ${{ if eq(parameter.environment, 'ptl') }}:
                  initCommandOptions:
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }}
                ${{ if eq(parameter.environment, 'prod') }}:
                  initCommandOptions:
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }}
